version: "3.9"

services:
  db:
    image: postgres:18
    container_name: smart-parking-db
    environment:
      POSTGRES_DB: parkinglot
      POSTGRES_USER: parking
      POSTGRES_PASSWORD: parking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: smart-parking-app
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/parkinglot
      SPRING_DATASOURCE_USERNAME: parking
      SPRING_DATASOURCE_PASSWORD: parking

volumes:
  pgdata: